---
source:
  db_system: postgres
  host: 127.0.0.1
  port: 5432
  user: user
  password: password
  dbname: source_db
  table: source_table
  transaction_column: transaction_column
  item_column: item_column
target:
  db_system: postgres
  host: 127.0.0.1
  port: 5432
  user: user
  password: password
  dbname: target_db
  table: target_table
  target_column: target_column
...