---
source:
  db_system: postgres
  host: 127.0.0.1
  port: 5432
  user: user
  password: password
  dbname: source_db
  table: source_table
  transaction_column: transaction_column
  item_column: item_column
target:
  db_system: neo4j
  host: 127.0.0.1
  port: 7687
  user: user
  password: password
mining_var:
  number_of_cases: no # support will be number of cases instead of percent if set to yes
  support: 10 # percent if use_number_of_case is set to no
  min_set: 1 # item(s)
  max_set: 5 # item(s)
preferences:
  print_rules_mine: yes
  save_to_target:
    rules_mine: no
    test_set: yes
...